server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: authx-mfa-system
  
  profiles:
    active: railway
  
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
  
  data:
    redis:
      url: ${REDIS_URL}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 4
          min-idle: 1
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days

# MFA Configuration
mfa:
  otp:
    expiration: ${OTP_EXPIRATION:300} # 5 minutes
    max-attempts: ${OTP_MAX_ATTEMPTS:3}
  webauthn:
    rp-id: ${WEBAUTHN_RP_ID}
    rp-name: ${WEBAUTHN_RP_NAME:AuthX MFA System}
    origin: ${WEBAUTHN_ORIGIN}

# Rate Limiting (production settings)
rate-limit:
  login:
    capacity: 100
    refill-tokens: 10
    refill-period: 60
  otp:
    capacity: 50
    refill-tokens: 1
    refill-period: 300
  mfa:
    verification:
      capacity: 30
      refill-tokens: 1
      refill-period: 600
    setup:
      capacity: 20
      refill-tokens: 1
      refill-period: 900
    preferred-method:
      capacity: 10
      refill-tokens: 1
      refill-period: 3600
  password-reset:
    capacity: 20
    refill-tokens: 1
    refill-period: 900

# SMS Configuration
sms:
  enabled: ${SMS_ENABLED:false}
  provider: ${SMS_PROVIDER:mock}
  twilio:
    account-sid: ${TWILIO_ACCOUNT_SID:}
    auth-token: ${TWILIO_AUTH_TOKEN:}
    from-number: ${TWILIO_FROM_NUMBER:}

# Logging
logging:
  level:
    com.authx: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
